[package]
name = "web_service_pratice"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
mongodb = "2.6.0"
serde = "1.0.180"
serde_json = "1.0.104"
async-trait = "0.1.72"
thiserror = "1.0.44"
anyhow = "1.0.72"